List<Map<String, String>> listType = [
  {"title": "Chi tiêu hàng tháng"},
  {"image": "assets/icons/eat.png", "title": "Ăn uống"},
  {"image": "assets/icons/taxi.png", "title": "Di chuyển"},
  {"image": "assets/icons/house.png", "title": "Thuê nhà"},
  {"image": "assets/icons/water.png", "title": "Tiền nước"},
  {"image": "assets/icons/phone.png", "title": "Tiền điện thoại"},
  {"image": "assets/icons/electricity.png", "title": "Tiền điện"},
  {"image": "assets/icons/gas.png", "title": "Tiền ga"},
  {"image": "assets/icons/tv.png", "title": "Tiền TV"},
  {"image": "assets/icons/internet.png", "title": "Tiền internet"},
  {"title": "Chi tiêu cần thiết"},
  {"image": "assets/icons/house_2.png", "title": "Sửa và trang trí nhà"},
  {"image": "assets/icons/tools.png", "title": "Bảo dưỡng xe"},
  {"image": "assets/icons/health-insurance.png", "title": "Khám sức khỏe"},
  // {"image": "assets/icons/", "title": ""},
  // {"image": "assets/icons/", "title": ""},
  // {"image": "assets/icons/", "title": ""},
  // {"image": "assets/icons/", "title": ""},
  // {"image": "assets/icons/", "title": ""},
  // {"image": "assets/icons/", "title": ""},
  // {"image": "assets/icons/", "title": ""},
  // {"image": "assets/icons/", "title": ""},
  // {"image": "assets/icons/", "title": ""},
];
