List<Map<String, String>> listType = [
  {"title": "Chi tiêu hàng tháng"},
  {"image": "assets/icons/eat.png", "title": "Ăn uống"},
  {"image": "assets/icons/taxi.png", "title": "Di chuyển"},
  {"image": "assets/icons/house.png", "title": "Thuê nhà"},
  {"image": "assets/icons/water.png", "title": "Tiền nước"},
  {"image": "assets/icons/phone.png", "title": "Tiền điện thoại"},
  {"image": "assets/icons/electricity.png", "title": "Tiền điện"},
  {"image": "assets/icons/gas.png", "title": "Tiền ga"},
  {"image": "assets/icons/tv.png", "title": "Tiền TV"},
  {"image": "assets/icons/internet.png", "title": "Tiền internet"},
  {"title": "Chi tiêu cần thiết"},
  {"image": "assets/icons/house_2.png", "title": "Sửa và trang trí nhà"},
  {"image": "assets/icons/tools.png", "title": "Bảo dưỡng xe"},
  {"image": "assets/icons/doctor.png", "title": "Khám sức khỏe"},
  {"image": "assets/icons/health-insurance.png", "title": "Bảo hiểm"},
  {"image": "assets/icons/education.png", "title": "Giáo dục"},
  {"image": "assets/icons/armchair.png", "title": "Đồ gia dụng"},
  {"image": "assets/icons/toothbrush.png", "title": "Đồ dùng cá nhân"},
  {"image": "assets/icons/pet.png", "title": "Thú cưng"},
  {"image": "assets/icons/family.png", "title": "Dịch vụ gia đình"},
  {"image": "assets/icons/box.png", "title": "Chi phí khác"},
  {"title": "Vui - chơi"},
  {"image": "assets/icons/sports.png", "title": "Thể thao"},
  {"image": "assets/icons/diamond.png", "title": "Làm đẹp"},
  {"image": "assets/icons/give-love.png", "title": "Quà tặng & Quyên góp"},
  {"image": "assets/icons/card-payment.png", "title": "Dịch vụ trực tuyến"},
  {"image": "assets/icons/game-pad.png", "title": "Vui - chơi"},
  {"title": "Đầu tư, Cho vay & Nợ"},
  {"image": "assets/icons/stats.png", "title": "Đầu tư"},
  {"image": "assets/icons/coins.png", "title": "Thu nợ"},
  {"image": "assets/icons/loan.png", "title": "Đi vay"},
  {"image": "assets/icons/borrow.png", "title": "Cho vay"},
  {"image": "assets/icons/pay.png", "title": "Trả nợ"},
  {"image": "assets/icons/commission.png", "title": "Trả lãi"},
  {"image": "assets/icons/percentage.png", "title": "Thu lãi"},
  {"title": "Khoản thu"},
  {"image": "assets/icons/money.png", "title": "Lương"},
  {"image": "assets/icons/money-bag.png", "title": "Thu nhập khác"},
  {"title": "Khác"},
  {"image": "assets/icons/wallet-symbol.png", "title": "Tiền chuyển đi"},
  {"image": "assets/icons/wallet.png", "title": "Tiền chuyển đến"},
  {"image": "assets/icons/plus.png", "title": "Nhóm mới"},
];
